---
name: Expo GitHub Action
author: Cedric van Putten <me@bycedric.com>
description: Expo CLI in your GitHub Actions workflow.
branding:
  icon: terminal
  color: gray-dark
runs:
  using: node12
  main: build/index.js
input:
  expo-version:
    description: The Expo CLI version to install. (use any semver/dist-tag available)
    default: latest
  expo-username:
    description: Your Expo username, for authentication.
  expo-password:
    description: Your Expo password, for authentication. (use with secrets)
  expo-packager:
    description: The package manager used to install the Expo CLI. (can be yarn or npm)
    default: npm
  expo-patch-watchers:
    description: If Expo should fix the default watchers limit, helps with ENOSPC errors. (can be true or false)
    default: true
  expo-cache:
    description: If Expo should be cached in your repo. (highly experimental, can be true or false)
    default: false
